const defaultMovies = [
  "Titanic",
  "The Shawshank Redemption",
  "Inception",
  "The Godfather",
  "Pulp Fiction",
  "Forrest Gump",
  "The Dark Knight",
  "Schindler's List",
  "The Lord of the Rings: The Return of the King",
  "Fight Club",
  "The Matrix",
  "Goodfellas",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "The Green Mile",
  "The Avengers",
  "Avatar",
  "The Lion King",
  "Gladiator",
  "The Departed",
  "The Prestige",
  "Interstellar",
  "The Social Network",
  "The Wolf of Wall Street",
  "The Grand Budapest Hotel",
  "Jurassic Park",
  "Inglourious Basterds",
  "The Revenant",
  "Forrest Gump",
  "La La Land",
  "The Godfather: Part II",
  "The Dark Knight Rises",
  "The Matrix Reloaded",
  "The Matrix Revolutions",
  "Jurassic World",
  "Finding Nemo",
  "Toy Story",
  "Toy Story 2",
  "Toy Story 3",
  "The Incredibles",
  "Ratatouille",
  "WALL-E",
  "Up",
  "Inside Out",
  "Coco",
  "Frozen",
  "Frozen II",
  "Moana",
  "Aladdin",
  "Beauty and the Beast",
  "The Little Mermaid",
  "Jaws",
  "E.T. the Extra-Terrestrial",
  "Indiana Jones and the Raiders of the Lost Ark",
  "The Shawshank Redemption",
  "The Godfather",
  "Schindler's List",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "Harry Potter and the Sorcerer's Stone",
  "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prisoner of Azkaban",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Order of the Phoenix",
  "Harry Potter and the Half-Blood Prince",
  "Harry Potter and the Deathly Hallows – Part 1",
  "Harry Potter and the Deathly Hallows – Part 2",
  "Star Wars: Episode IV - A New Hope",
  "Star Wars: Episode V - The Empire Strikes Back",
  "Star Wars: Episode VI - Return of the Jedi",
  "Star Wars: Episode I - The Phantom Menace",
  "Star Wars: Episode II - Attack of the Clones",
  "Star Wars: Episode III - Revenge of the Sith",
  "Star Wars: The Force Awakens",
  "Star Wars: The Last Jedi",
  "Star Wars: The Rise of Skywalker",
  "Indiana Jones and the Temple of Doom",
  "Indiana Jones and the Last Crusade",
  "The Hunger Games",
  "The Hunger Games: Catching Fire",
  "The Hunger Games: Mockingjay – Part 1",
  "The Hunger Games: Mockingjay – Part 2",
];
